# Generated by Django 4.0.1 on 2022-02-06 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=datetime.datetime(2022, 2, 6, 17, 27, 26, 578511))),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_tipo', to='pagos.tipopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
