# Generated by Django 4.0.1 on 2022-01-21 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_tipopago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 17, 27, 25, 313481)),
        ),
    ]
