# Generated by Django 4.0.1 on 2022-03-08 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0017_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 12, 55, 13, 477878)),
        ),
    ]
