# Generated by Django 4.0.1 on 2022-03-08 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0021_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopago',
            name='duracion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 13, 0, 32, 564948)),
        ),
    ]
