# Generated by Django 4.0.1 on 2022-01-21 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_asistencia_fecha_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 17, 23, 14, 572764)),
        ),
    ]
