# Generated by Django 4.0.1 on 2022-03-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='horario_fin',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_inicio',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
