# Generated by Django 4.0.1 on 2022-02-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
