# Generated by Django 4.0.1 on 2022-02-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_cierrecaja_created_at_alter_cierrecaja_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
